# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a74dee2d70c6af4f09ca02e3b713253ac698f5d4751d77278a04c3230618553059d51e4cdede095bb16163a17ab8d4f48cc5d41e372eede193ace50a0ab718

test:
  secret_key_base: 688ed520aea9fbbec97de7773c5f1c64bf1348d9d2def2d7952f2993f21281cc2c432dcfe3c763b66828df1819f2a4617d278862927be3f3539b8f212ad1ea07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
